package com.phantomdroid.app;

import android.content.Context;
import android.os.Environment;

import java.io.File;
import java.io.FileWriter;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.Map;

public class ReportGenerator {

    private final DatabaseHelper dbHelper;
    private final Context context;

    public ReportGenerator(Context context, DatabaseHelper dbHelper) {
        this.context = context;
        this.dbHelper = dbHelper;
    }

    /** Generate the full 24-hour Markdown report and save to Documents folder.
     *  Returns the absolute file path on success, null on failure. */
    public String generateReport() {
        try {
            long startTime = dbHelper.getSessionStartTime();
            int totalEvents = dbHelper.getTotalLogCount();
            int uniqueApps = dbHelper.getUniqueAppCount();
            Map<String, Integer> appCounts = dbHelper.getAppUsageCounts();
            List<String[]> allLogs = dbHelper.getAllLogs();

            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.getDefault());
            SimpleDateFormat fileSdf = new SimpleDateFormat("yyyy-MM-dd_HHmm", Locale.getDefault());
            String startStr = startTime > 0 ? sdf.format(new Date(startTime)) : "Unknown";
            String endStr = sdf.format(new Date());

            StringBuilder md = new StringBuilder();

            // Header
            md.append("# PhantomDroid 24-Hour Privacy Report\n\n");
            md.append("**Generated:** ").append(endStr).append("\n\n");
            md.append("---\n\n");

            // Summary
            md.append("## Summary\n\n");
            md.append("| Metric | Value |\n");
            md.append("|--------|-------|\n");
            md.append("| Monitor Start | ").append(startStr).append(" |\n");
            md.append("| Monitor End | ").append(endStr).append(" |\n");
            md.append("| Total Events Recorded | ").append(totalEvents).append(" |\n");
            md.append("| Unique Apps Detected | ").append(uniqueApps).append(" |\n");
            md.append("\n---\n\n");

            // App Usage Ranking
            md.append("## App Usage Ranking\n\n");
            md.append("Apps ranked by how many times they were detected in the foreground:\n\n");
            md.append("| Rank | App | Times Opened |\n");
            md.append("|------|-----|--------------|\n");
            int rank = 1;
            for (Map.Entry<String, Integer> entry : appCounts.entrySet()) {
                String appName = entry.getKey();
                // Clean up package names for readability
                if (appName.contains(".")) {
                    String[] parts = appName.split("\\.");
                    appName = parts[parts.length - 1]; // last segment
                }
                md.append("| ").append(rank++).append(" | ").append(appName)
                        .append(" | ").append(entry.getValue()).append(" |\n");
                if (rank > 50) break; // cap at 50 apps
            }
            md.append("\n---\n\n");

            // Full package names for reference
            md.append("## Full Package Names\n\n");
            md.append("These are the real Android package identifiers for each app detected:\n\n");
            for (Map.Entry<String, Integer> entry : appCounts.entrySet()) {
                md.append("- `").append(entry.getKey()).append("` (").append(entry.getValue()).append(" events)\n");
            }
            md.append("\n---\n\n");

            // Recent Activity Log (last 200 events)
            md.append("## Activity Log (Most Recent 200 Events)\n\n");
            md.append("| Time | App | Event |\n");
            md.append("|------|-----|-------|\n");
            int logCount = 0;
            for (String[] log : allLogs) {
                md.append("| ").append(log[0]).append(" | ").append(log[1])
                        .append(" | ").append(log[2]).append(" |\n");
                if (++logCount >= 200) break;
            }
            md.append("\n---\n\n");

            // Footer
            md.append("## About This Report\n\n");
            md.append("This report was generated by **PhantomDroid V3** running as an Accessibility Service on your Android device. ");
            md.append("It records every time an app opens in the foreground over a 24-hour period. ");
            md.append("This data can reveal hidden patterns in app usage, background activity, and potential privacy concerns.\n\n");
            md.append("> **Note**: This report only captures foreground app transitions. ");
            md.append("Background services, network calls, and microphone access require additional system-level permissions.\n");

            // Save to Documents folder
            File docsDir = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOCUMENTS);
            if (!docsDir.exists()) docsDir.mkdirs();

            String fileName = "PhantomDroid_Report_" + fileSdf.format(new Date()) + ".md";
            File reportFile = new File(docsDir, fileName);

            FileWriter writer = new FileWriter(reportFile);
            writer.write(md.toString());
            writer.close();

            return reportFile.getAbsolutePath();

        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }
}
